### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by k1o0**
Added tests for most Alyx methods and also numerous fixes for bugs exposed by testing framework.

Still todo:
- [ ] Add tests for +alf/block2Alf
- [ ] Add test method for @Alyx/registerFile
- [ ] Add test method for @Alyx/getFiles
- [ ] Expend tests for @Alyx/getSessions

### CODE REVIEW

**Comment by jaib1** [comment]
do you want to update the file and filename structure for tests here in alyx-matlab to follow the same conventions used in Rigbox? (i.e. naming test files with '_test' and creating a 'tests' folder and potentially a 'fixtures' folder)

**Comment by k1o0** [comment]
Sure, I'm happy to do that

**Comment by k1o0** [comment]
Okay it's ready to merge.

**Comment by jaib1** [comment]
done - rebased and merged in command line.

**Pull request closed without merging**
