### PR TITLE
Added support for local network repos

### PR DESCRIPTION
**Pull request by k1o0**

### CODE REVIEW

**Comment by k1o0** [comment]
@nsteinme This fix allows one to use the getFile method to retrieve file paths from non-http repos (previously only returned paths from repos that had a `data_url` field that wasn't `null`).  This is another step towards using Alyx instead of the dat package (#30).

**Comment by nsteinme** [comment]
One observation: there's a dependency on rigbox here. is that intentional? (also I don't really understand why this line is defaulting to https - seems like a hack for cortexlab?) 

Undefined function or variable 'iff'.
Error in Alyx/set.BaseURL (line 99)
      value = iff(value(1:4)~='http', ['https://' value], value);

**Comment by nsteinme** [comment]
Another observation, the fact that you have these "tests" and "fixtures" in the rigbox repo is really confusing/problematic, because you can't just add rigbox to the path and expect it to work - the dat.paths from the tests will override the real dat.paths and everything will break. Note that I only lost the last 20 minutes figuring this out because rigbox was a dependency, which I recommend that it not be.

**Comment by nsteinme** [comment]
Ok, so I still get the same problem, see below. Note that the file_record's data_repository_path is empty. 

```
>> sess = ai.getSessions('subject', 'AD_0001')

sess = 

  38×1 struct array with fields:

    lab
    number
    start_time
    subject
    url

>> s = sess(11)

s = 

  struct with fields:

           lab: 'steinmetzlab'
        number: 1
    start_time: '2019-09-09T16:07:24'
       subject: 'AD_0001'
           url: 'http://alyx.steinmetzlab.net/sessions/78dfc96e-01ef-4f8f-b5fa-410bd8124cb2'

>> [fullpath, filename, fileID, records] = ai.expFilePath(s.subject, s.start_time(1:10), s.number, 'Block')

fullpath =

    'AD_0001/2019-09-09/1/2019-09-09_1_AD_0001_Block.mat'


filename =

    '2019-09-09_1_AD_0001_Block.mat'


fileID =

    '7e50caff-9176-44d7-b983-28d6c49f19e6'


records = 

  struct with fields:

                  url: 'http://alyx.steinmetzlab.net/datasets/7ec25821-75a3-40f8-81cb-2f0b0c55c5f9'
                 name: '2019-09-09_1_AD_0001_Block.mat'
           created_by: 'nick'
     created_datetime: '2019-09-09T16:52:35.382514'
         dataset_type: 'block'
          data_format: 'mat file'
              session: 'http://alyx.steinmetzlab.net/sessions/78dfc96e-01ef-4f8f-b5fa-410bd8124cb2'
            file_size: []
                  md5: []
    experiment_number: 1
         file_records: [1×1 struct]

>> records.file_records

ans = 

  struct with fields:

                      id: '7e50caff-9176-44d7-b983-28d6c49f19e6'
         data_repository: 'steinmetzsuper1'
    data_repository_path: ''
           relative_path: 'AD_0001/2019-09-09/1/2019-09-09_1_AD_0001_Block.mat'
                data_url: []
                  exists: 1

```

**Comment by nsteinme** [comment]
Note also that there is a bug, or at least what would be a useful feature, in that you can't use `s.start_time` when asking for the block file - that's why above I used `s.start_time(1:10)`

```
>> [fullpath, filename, fileID, records] = ai.expFilePath(s.subject, s.start_time, s.number, 'Block')
Error using datestr (line 182)
Cannot convert input into specified date character vector.
DATENUM failed.

Error in Alyx/expFilePath (line 69)
  expDate = datestr(expDate, 'yyyy-mm-ddTHH:MM:SS');
```

**Comment by k1o0** [comment]
> One observation: there's a dependency on rigbox here. is that intentional? (also I don't really understand why this line is defaulting to https - seems like a hack for cortexlab?)
> 
> Undefined function or variable 'iff'.
> Error in Alyx/set.BaseURL (line 99)
> value = iff(value(1:4)~='http', ['https://' value], value);

1. Yes I opened an issue on dependencies here: https://github.com/cortex-lab/Rigbox/issues/81.  Currently no one really uses signals and alyx-matlab on their own so I've not been strict about keeping them independent.  All three share functions that are in cb-tool / burgbox which actually has its own repo [here](https://github.com/cortex-lab/MATLAB-tools), so it could be made into a shared dependency.  The problem with that is we'd have to instruct people to install it separately (we wouldn't want it as a triplicated submodule).  Originally Chris just copied the functions like `iff` into the Signals repo but this isn't ideal either.  If you have any comments on this let me know.

2. The https certainly isn't a hack.  This behaviour is the same as that of any modern browser: if you add a url as `http://` then it uses this, otherwise it prepends `https://` automatically.  It's pretty easy to add certificates to your server and I recommend you do it.  It is a hack insofar as the IBL alyx used to fail if you didn't connect explicitly via https.  I'll add something in the paths template and documentation about this to make it clearer.  I can also add a paths template to the alyx-matlab and signals repos.

> Another observation, the fact that you have these "tests" and "fixtures" in the rigbox repo is really confusing/problematic, because you can't just add rigbox to the path and expect it to work - the dat.paths from the tests will override the real dat.paths and everything will break. Note that I only lost the last 20 minutes figuring this out because rigbox was a dependency, which I recommend that it not be.

I won't change this behaviour, it's too difficult otherwise.  We have `addRigboxPaths` for a reason and the instructions are pretty clear in the readme and documentation.  A couple of weeks ago I wrote a huge about of documentation on setting up Rigbox and how various things work.  I'll make this more explicit and can also add an assert in the test paths so that an error is thrown when the paths file is called outside of the test environment.  The paths have always been the number one most frequent cause of problems for people, so I'll definitely add more extensive documentation on troubleshooting things.


> Note also that there is a bug, or at least what would be a useful feature, in that you can't use `s.start_time` when asking for the block file - that's why above I used `s.start_time(1:10)`

Good point.  Alyx has a static method for converting Alyx timestamps to datenums (`Alyx/datenum`) but I can add something in the methods to detect the format and do it automatically.  


> Ok, so I still get the same problem, see below. Note that the file_record's data_repository_path is empty.
>  
>  [fullpath, filename, fileID, records] = ai.expFilePath(s.subject, s.start_time(1:10), s.number, 'Block')
> 
> fullpath =
> 
>     'AD_0001/2019-09-09/1/2019-09-09_1_AD_0001_Block.mat'
> 
OK I think the problem here is that your hostname field is empty?  In data repositories add a hostname for `steinmetzsuper1` without `\\` or `http://`.  

Unfortunately I've just discovered a problem with this.  I thought it was working when I tried it a few weeks ago but either the database changed or I'm misremembering (probably the latter).  Anyway I'm seeing this which is obviously trash: 
```
fullPath =

    '\\zserver.cortexlab.netKM007/2019-09-13/1/2019-09-13_1_KM007_Block.mat'
```

The slashes can easily be changed but there's currently no way of indicating the `Data\Subjects\` part in Alyx.  I will discuss this with Olivier and see if we can find a solution to this.

**Comment by k1o0** [comment]
Hmm I see you do have the hostname field...

**Comment by k1o0** [comment]
A number of things appear to be issues with current state of Alyx:
1. for the datasets endpoint you can't filter by experiment date, only the datetime (this behaviour is weird and inconsistent, see https://github.com/cortex-lab/alyx/issues/601).  I've added a hack that works around this issue but it's about 3 seconds slower.

2. the data repositories table has a data_url field which is a complete uri then in has relative_path and globus_path fields which you have to use to construct your own complete path.  This seems wrong to me but it's unlikely to change.

3. the globus_path field is called data_repository_path in associated tables such as filerecords.  

4. the data repositories table doesn't allow multiple paths so if we use globus we can't make any other mount points without doing lab/protocol/OS specific regex on the data returned by alyx.

For these reasons we can't replace the dat package with database queries so I'll leave the methods as they are here which now faithfully return whatever is set in the data repository table.

I'll go ahead and merge into dev next week but I'll keep this PR open until point 1 is resolved.  Feel free to try it out.

**Pull request merged**
