### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by k1o0**
I've removed some files that I think are no longer used.  I'm unsure about the alyxIO package though.  If you still use this I'll keep it in...

### CODE REVIEW

**Comment by nsteinme** [comment]
Please do NOT remove alyxIO and alyxEphys. I use those. If you're sure about the other ones not being used then fine with me to remove, though why not just put them into a folder called something like "archive" or something? 

Miles you're becoming like Matteo walking into an experimental room: "Hm, I haven't looked around here in a while, I bet no one uses any of this. Let's just dump the things I don't like into some bins..." ;)

**Comment by jaib1** [comment]
```
Miles you're becoming like Matteo walking into an experimental room: "Hm, I haven't looked around here in a while, I bet no one uses any of this. Let's just dump the things I don't like into some bins..." ;)
```
Mm maybe I'm finally rubbing off on Miles!

**Comment by k1o0** [comment]
Ain't no thing, Nick! I'm just chasing that full coverage rainbow.  Aside from your two packages everything else uses functions that no longer exist.  There's no need to archive them - they'll be on Git forever.

**Comment by k1o0** [comment]
@nsteinme ready for your review, sir

**Pull request merged**
